title: Memorise o c칩digo
description: "O site Memorise o c칩digo nasceu com o intuito de compartilhar o conhecimento de Git, Python e de diversas outras linguagens de c칩digo, j치 citados anteriormente."
favicon: "https://raw.githubusercontent.com/Memorise-codigos/memorise-codigos.github.io/main/favicon.ico"
theme: minima
